"use client";

import { motion } from "framer-motion";

const reasons = [
  {
    title: "Human-Centered AI",
    description:
      "CrimeLens AI was designed to assist investigators rather than replace them. Every recommendation generated by the system is intended to support human decision-making while keeping investigators in complete control of the case.",
  },
  {
    title: "Research Before Development",
    description:
      "The project began with studying NCRB cybercrime reports, Smart Policing initiatives, existing investigative workflows, and common operational challenges faced during cybercrime investigations.",
  },
  {
    title: "Modular Intelligence",
    description:
      "Instead of relying on a single large AI model, CrimeLens adopts a modular architecture where specialized AI agents perform dedicated responsibilities before collaborating to produce a unified investigation report.",
  },
  {
    title: "Future Scalability",
    description:
      "The architecture was intentionally designed to allow future integration of additional AI agents, forensic tools, OCR pipelines, speech processing, malware analysis, and external intelligence sources without redesigning the system.",
  },
];

export default function WhyCrimeLens() {
  return (
    <section className="mx-auto max-w-7xl px-8 py-40">

      <motion.div
        initial={{ opacity: 0, y: 60 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >

        <p className="uppercase tracking-[0.35em] text-blue-400">
          Design Philosophy
        </p>

        <h2 className="mt-6 text-6xl font-black">
          Why CrimeLens AI?
        </h2>

        <p className="mt-10 max-w-5xl text-xl leading-10 text-gray-400">

          CrimeLens AI was never intended to be "another chatbot."

          <br /><br />

          The objective was to research how Artificial Intelligence could
          become a dependable investigative assistant capable of reducing
          repetitive work, organizing evidence, and providing meaningful
          insights while ensuring that investigators remain responsible for
          every operational decision.

          <br /><br />

          Every architectural decision was made with scalability,
          explainability, and practical usability in mind.

        </p>

      </motion.div>

      <div className="mt-24 grid gap-8 lg:grid-cols-2">

        {reasons.map((reason, index) => (

          <motion.div
            key={reason.title}
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{
              delay: index * 0.08,
            }}
            whileHover={{
              y: -8,
              scale: 1.02,
            }}
            className="rounded-3xl border border-white/10 bg-white/5 p-10 backdrop-blur-xl"
          >

            <div className="flex items-center gap-5">

              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-blue-500/10 text-xl font-bold text-blue-400">

                {index + 1}

              </div>

              <h3 className="text-3xl font-bold">
                {reason.title}
              </h3>

            </div>

            <p className="mt-8 leading-9 text-gray-400">
              {reason.description}
            </p>

          </motion.div>

        ))}

      </div>

      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        className="mt-32 rounded-[40px] border border-blue-500/20 bg-gradient-to-r from-blue-500/10 via-white/5 to-blue-500/10 p-16"
      >

        <h3 className="text-center text-4xl font-bold leading-tight">

          CrimeLens AI combines
          <span className="text-blue-400"> Artificial Intelligence</span>,
          <span className="text-blue-400"> Cybersecurity</span>,
          <span className="text-blue-400"> Digital Investigation</span>,
          and
          <span className="text-blue-400"> Human Decision Making</span>
          into a single research platform.

        </h3>

      </motion.div>

    </section>
  );
}